### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [jnewmano/grpc-json-proxy#15]
I found that this project already [supports Go modules](https://github.com/jnewmano/grpc-json-proxy/blob/master/go.mod). But sadly, the [tags](https://github.com/jnewmano/grpc-json-proxy/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
	github.com/jnewmano/grpc-json-proxy v0.0.0-20200427184142-6696b5a3ab05
```
Else the mod file shows something like `github.com/jnewmano/grpc-json-proxy v0.0.0-20200427184142-6696b5a3ab05` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control.

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc.

**Comment by KateGo520** [comment]
@vincenthcui  @kevinswiber Could you help me review this issue? Thx :p

**Comment by vincenthcui** [comment]
Hi @KateGo520, I'm so glad to help but have no permission to tag this repository. Maybe @kevinswiber can come by and re-tag a semantic version.

**Comment by jnewmano** [comment]
Tag `v0.0.2` has been added.
